on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo gem install bundler  
          bundle install
      
      - name: "Setup XCode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: Build and test
        run: bundle exec fastlane test
